src/Entity/Avatar.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\AvatarRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: AvatarRepository::class)]
class Avatar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10)]
    #[Assert\Length(
        min: 2,
        max: 10,
        minMessage: 'Your label must be at least {{ limit }} characters long',
        maxMessage: 'Your label cannot be longer than {{ limit }} characters',
    )]
    private ?string $label = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[Vich\UploadableField(mapping: 'avatar', fileNameProperty: 'url')]
    private ?File $avatarFile = null;

    #[ORM\OneToMany(mappedBy: 'avatar', targetEntity: User::class)]
    private Collection $user;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable();
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
            $user->setAvatar($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getAvatar() === $this) {
                $user->setAvatar(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->label;
    }

    /**
     * Get the value of avatarFile
     *
     * @return ?File
     */
    public function getAvatarFile(): ?File
    {
        return $this->avatarFile;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $avatarFile
     */
    public function setAvatarFile(?File $avatarFile = null): void
    {
        $this->avatarFile = $avatarFile;

        if (null !== $avatarFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
           // $this->upload_at = new \DateTimeImmutable();
        }
    }

    /**
     * Get the value of created_at
     *
     * @return ?\DateTimeImmutable
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    /**
     * Set the value of created_at
     *
     * @param ?\DateTimeImmutable $created_at
     *
     * @return self
     */
    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 3,
        max: 50,
        minMessage: 'Your first name must be at least {{ limit }} characters long',
        maxMessage: 'Your first name cannot be longer than {{ limit }} characters',
    )]

    private ?string $title = null;
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(
        min: 5,
        max: 255,
        minMessage: 'Your first name must be at least {{ limit }} characters long',
        maxMessage: 'Your first name cannot be longer than {{ limit }} characters',
    )]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $upload_at = null;

    #[ORM\Column(length: 255,nullable:true)]
    #[Assert\NotBlank()]
    private ?string $url = null;
    
    #[Vich\UploadableField(mapping: 'postThumbnail', fileNameProperty: 'url')]
    private ?File $postThumbnail = null;

    #[ORM\OneToMany(mappedBy: 'image', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\ManyToOne]
    private ?Category $category = null;

    #[ORM\ManyToOne]
    private ?User $userImage = null;
 

    public function __construct()
    {
        $this->upload_at = new DateTimeImmutable();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUploadAt(): ?\DateTimeImmutable
    {
        return $this->upload_at;
    }

    public function setUploadAt(\DateTimeImmutable $upload_at): self
    {
        $this->upload_at = $upload_at;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setImage($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getImage() === $this) {
                $comment->setImage(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUserImage(): ?User
    {
        return $this->userImage;
    }

    public function setUserImage(?User $userImage): self
    {
        $this->userImage = $userImage;

        return $this;
    }

    /**
     * Get the value of postThumbnail
     *
     * @return ?File
     */
    public function getPostThumbnail(): ?File
    {
        return $this->postThumbnail;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setPostThumbnail(?File $postThumbnail = null): void
    {
        $this->postThumbnail = $postThumbnail;

        if (null !== $postThumbnail) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->upload_at = new \DateTimeImmutable();
        }
    }
}

src/Form/ImageType.php
<?php

namespace App\Form;

use App\Entity\Image;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ImageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => '3',
                    'maxlength' => '50',

                ],
                'label' => 'Title',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 2, 'max' => 50]),
                    new Assert\NotBlank()
                ]
            ])

            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => '5',
                    'maxlength' => '255',

                ],
                'label' => 'Description',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Assert\Length(['min' => 5, 'max' => 255]),
                    new Assert\NotBlank()
                ]
            ])

            ->add('postThumbnail', VichImageType::class, [
                'attr' => [
                    'class' => 'form-control',
                ],
                'label' => 'Thumbnail',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'delete_label' => 'Remove avatar ',
                'download_uri' => false
            ])
            
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'label',
                'attr' => [
                    'class' => 'list-group mt-4'
                ],
                'row_attr' => [
                    'class' => 'mt-4'
                ],
            ])

            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary my-4'
                ],  'label' => 'Submit'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Image::class,
        ]);
    }
}

src/Controller/Image/DeleteController.php
<?php

namespace App\Controller\Image;

use App\Entity\Image;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeleteController extends AbstractController
{
    /**
     * This route delete a post if found. If not redirect to the home with a flash error.
     */
    #[route('image/delete/{id}', 'image.delete', methods: ['GET'])]
    public function delete(Image $image, EntityManagerInterface $manager): Response
    {
        if (!$image) {
            $this->addFlash(
                'error',
                'Ce post est introuvable !'
            );

            return $this->redirectToRoute('home');
        }

        $manager->remove($image);
        $manager->flush();

        $this->addFlash(
            'success',
            'Ce post a bien été effacé !'
        );
        
        return $this->redirectToRoute('home');
    }
}

src/Controller/Image/NewController.php
<?php

namespace App\Controller\Image;

use App\Entity\Image;
use App\Form\ImageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class NewController extends AbstractController
{
    #[Route('image/new','image.new',methods:['GET','POST'])]
    public function new(Request $request, EntityManagerInterface $manager):Response
    {
        $image = new Image();
        $form = $this->createForm(ImageType::class,$image);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $image= $form->getData();

            $manager->persist($image);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre image a été uploadé avec succès !'
            );

           return $this->redirectToRoute('home',['_fragment' => $image->getId()]);
        }

        return $this->render('pages/images/new-update.html.twig',['form' => $form->createView(),'label'=>'create']);
    }
}

src/Controller/Image/ShowController.php
<?php

namespace App\Controller\Image;

use App\Entity\Comment;
use App\Entity\Image;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShowController extends AbstractController
{

    #[route('image/show/{id}', 'image.show', methods: ['GET', 'POST'])]
    public function show(Image $image, Request $request, EntityManagerInterface $manager): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $form->getData();
            //Link the comment with the actual post.
            $comment->setImage($image);

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash('success', 'Votre commentaire a bien été posté');
        }

        return $this->render('pages/images/show.html.twig', ['form' => $form->createView(), 'image' => $image]);
    }
}

src/Controller/Image/UpdateController.php
<?php

namespace App\Controller\Image;

use App\Entity\Image;
use App\Form\ImageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class UpdateController extends AbstractController
{
    #[route('/image/update/{id}','image.update',methods:['GET','POST'])]
    public function update(EntityManagerInterface $manager,Image $image,Request $request){

        $form = $this->createForm(ImageType::class,$image);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $image = $form->getData();
            $manager->persist($image);
            $manager->flush();

            $this->addFlash('success','Votre post a bien été modifié !');

            return $this->redirectToRoute('home',['_fragment' => $image->getId()]);
        }

        return $this->render('pages/images/new-update.html.twig',['form'=>$form->createView(),'label'=>'update']);
    }

}

templates/pages/images/new.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{parent()}}
	- Upload une image
{% endblock %}

{% block content %}
	<div class="container">

		<h1 class="mt-4">Upload d'une image.</h1>
		<div>

			{{ form_start(form) }}


			<div class="form-group">
				{{form_label(form.title)}}
				{{form_widget(form.title)}}
				<div class="form-error">
					{{ form_errors(form.title) }}
				</div>
			</div>

			<div class="form-group">
				{{form_label(form.description)}}
				{{form_widget(form.description)}}
				<div class="form-error">
					{{ form_errors(form.description) }}
				</div>
			</div>

			<div class="form-group">
				{{form_label(form.url)}}
				{{form_widget(form.url)}}
				<div class="form-error">
					{{ form_errors(form.url) }}
				</div>
			</div>

			<div class="form-group">
				{{form_label(form.submit)}}
			</div>


		</div>
		{{ form_end(form) }}


	</div>
</div>{% endblock %}

templates/pages/images/post.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{parent()}}
	- {{label}} a post
{% endblock %}

{% block content %}
	<div class="container">

		<h1 class="mt-4">{{label}} a post.</h1>
		<div>

			{{ form_start(form) }}


			<div class="form-group">
				{{form_label(form.title)}}
				{{form_widget(form.title)}}
				<div class="form-error">
					{{ form_errors(form.title) }}
				</div>
			</div>

			<div class="form-group">
				{{form_label(form.description)}}
				{{form_widget(form.description)}}
				<div class="form-error">
					{{ form_errors(form.description) }}
				</div>
			</div>

			<div class="form-group">
				{{form_label(form.url)}}
				{{form_widget(form.url)}}
				<div class="form-error">
					{{ form_errors(form.url) }}
				</div>
			</div>

			<div class="form-group">
				{{form_label(form.submit)}}
			</div>


		</div>
		{{ form_end(form) }}


	</div>
</div>{% endblock %}

templates/pages/images/show.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{parent()}}
	- Post
	{{image.title}}
{% endblock %}


{% block content %}

	{# Flash #}
	<div class="container-fluid">
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">
				{{message}}
			</div>
		{% endfor %}

		<div
			class="card text-white bg-primary mt-4 mb-4 col-lg-12 mx-auto rounded" style="max-width:600px">

			{# Category #}
			{% if image.category %}
				<div class="card-header text-end">
					<span class="badge bg-info px-2 py-3 rounded">{{image.category.label}}</span>
				</div>
			{% endif %}

			{# Post #}
			<div class="card-body ">
				<div class="text-center">
					<h4 class="card-title">{{image.title|upper}}</h4>

					<img src="{{image.url}}" width="300" height="300" class="rounded">
				</div>
				<p>By
					<strong>user</strong>
					at
					{{image.uploadAt|date('d/m/Y')}}</p>
				<p class="card-text mt-4">{{image.description}}</p>

				<div>
					<a href="{{path('image.update',{id:image.id})}}">
						<button type="button" class="btn btn-secondary">Edit</button>
					</a>
					<a href="{{path('image.delete',{id:image.id})}}">
						<button type="button" class="btn btn-danger">Delete</button>
					</a>
					<hr>
				</div>

				{# Comments #}
				<div class="mt-4" id="comments">
					{% if image.comments|length>0 %}
						<h2 class="mb-4 text-center">{{image.comments|length}}
							Comment{{image.comments|length>1?'s':''}}
							:</h2>
						{% for comment in image.comments %}

							<p class="my-2" id="{{comment.id}}">By
								<strong>{{comment.userComment.pseudo|capitalize}}</strong>
								at
								{{comment.createdAt|date('m/d/Y h:m')}}</p>
							<p>{{comment.message}}</p>
							<hr>

						{% endfor %}

					{% else %}
						<p>No commentary yet, be the first to post one !</p>
					{% endif %}
					
					{# form comment #}
					{{ include('comment/_form.html.twig') }}
					<div class="text-center">
						<a href="{{path('home')}}#{{image.id}}">
							<button class="btn btn-secondary hBack" type="button">Back</button>
						</a>
					</div>
				</div>
			</div>
		</div>

	</div>
{% endblock %}